config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
	#mount Soulmate::Server, :at => "/autocomplete"

	root 'home#index'

	get '/list' => 'battles#list', as: :list

	get '/count' => 'battles#count', as: :count

	get '/search' => 'battles#search', :as => :search

	get '/stats' => 'battles#stats', as: :stats


  	resources :battles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord
	after_save :load_into_soulmate
	before_destroy :remove_from_soulmate

	def self.search(search)
		  where("name LIKE ? OR attacker_king LIKE ? OR defender_king LIKE ? OR battle_type LIKE ? OR location LIKE ?" , "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
		  
	end

	

	private 



	def load_into_soulmate
		loader = Soulmate::Loader.new("battles")
		loader.add("term" => name, "id" => self.id, "data" => {
			"link" => Rails.application.routes.url_helpers.battle_path(self)
	   	})
	end

	def remove_from_soulmate
		loader = Soulmate::Loader.new("battles")
	    loader.remove("id" => self.id)
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :set_battle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:list, :count, :stats]
  layout 'battles'
  # GET /battles
  # GET /battles.json
  def index
    @battles = Battle.all
  end

  # GET /search
  def search
    @battles = Battle.search(params[:search])
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /stats
  # GET /stats.json
  def stats

    @most_active_attk = Battle.group(:attacker_king).order('count_id DESC').count(:id).keys
    @most_active_defk = Battle.group(:defender_king).order('count_id DESC').count(:id).keys
    @most_active_region = Battle.group(:region).order('count_id DESC').count(:id).keys
    @most_active_name = Battle.group(:name).order('count_id DESC').count(:id).keys
    @battle_type = Battle.group(:battle_type).order('count_id DESC').count(:id)
    @max_def_size = Battle.group(:defender_size).order('defender_size DESC').count(:defender_size).keys
    @min_def_size = Battle.group(:defender_size).order('defender_size ASC').count(:defender_size).keys
    @battles = Battle.all
    @i = 0
    @sum = 0
    @min_def_size.each do |n|
      if n == nil
        @sum += 0
        @i += 0 
      else
        @sum += n 
        @i += 1
      end 

  end 

  end

  # GET /battles/1
  # GET /battles/1.json
  def show
  end

  # GET /battles/new
  def new
    @battle = Battle.new
  end

  # GET /battles/1/edit
  def edit
  end

  
  # GET /list.json
  def list
    @battles = Battle.all

    respond_to do |format|
      
      format.json
    end
  end

  # GET /count
  # GET /count.json
  def count
    @battles_count = Battle.all
    respond_to do |format|
      format.html
      format.json
    end
  end

  # POST /battles
  # POST /battles.json
  def create
    @battle = Battle.new(battle_params)

    respond_to do |format|
      if @battle.save
        format.html { redirect_to @battle, notice: 'Battle was successfully created.' }
        format.json { render :show, status: :created, location: @battle }
      else
        format.html { render :new }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /battles/1
  # PATCH/PUT /battles/1.json
  def update
    respond_to do |format|
      if @battle.update(battle_params)
        format.html { redirect_to @battle, notice: 'Battle was successfully updated.' }
        format.json { render :show, status: :ok, location: @battle }
      else
        format.html { render :edit }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /battles/1
  # DELETE /battles/1.json
  def destroy
    @battle.destroy
    respond_to do |format|
      format.html { redirect_to battles_url, notice: 'Battle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_battle
      @battle = Battle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def battle_params
      params.require(:battle).permit(:name, :year, :battle_number, :attacker_king, :defender_king, :attacker_1, :defender_1, :battle_outcome, :battle_type, :major_deaths, :major_capture, :attacker_size, :defender_size, :attacker_commander, :defender_commander, :summer, :location, :region, :note)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout 'home'
	
  def index
  	@battle = Battle.search(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/battles/_battles.html.erb
<p id="notice"><%= notice %></p>

<h1>Battles</h1>

<table class="highlight">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Battle number</th>
      <th>Attacker king</th>
      <th>Defender king</th>
      <th>Attacker 1</th>
      <th>Defender 1</th>
      <th>Battle outcome</th>
      <th>Battle type</th>
      <th>Major deaths</th>
      <th>Major capture</th>
      <th>Attacker size</th>
      <th>Defender size</th>
      <th>Attacker commander</th>
      <th>Defender commander</th>
      <th>Summer</th>
      <th>Location</th>
      <th>Region</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @battles.each do |battle| %>
      <tr>
        <td><%= battle.name %></td>
        <td><%= battle.year %></td>
        <td><%= battle.battle_number %></td>
        <td><%= battle.attacker_king %></td>
        <td><%= battle.defender_king %></td>
        <td><%= battle.attacker_1 %></td>
        <td><%= battle.defender_1 %></td>
        <td><%= battle.battle_outcome %></td>
        <td><%= battle.battle_type %></td>
        <td><%= battle.major_deaths %></td>
        <td><%= battle.major_capture %></td>
        <td><%= battle.attacker_size %></td>
        <td><%= battle.defender_size %></td>
        <td><%= battle.attacker_commander %></td>
        <td><%= battle.defender_commander %></td>
        <td><%= battle.summer %></td>
        <td><%= battle.location %></td>
        <td><%= battle.region %></td>
        <td><%= battle.note %></td>
        <td><%= link_to 'Show', battle %></td>
        <td><%= link_to 'Edit', edit_battle_path(battle) %></td>
        <td><%= link_to 'Destroy', battle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Battle', new_battle_path %>

app/views/battles/_form.html.erb
<%= form_for(battle) do |f| %>
  <% if battle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
      <% battle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <%= f.label :battle_number %>
    <%= f.number_field :battle_number %>
  </div>

  <div class="field">
    <%= f.label :attacker_king %>
    <%= f.text_field :attacker_king %>
  </div>

  <div class="field">
    <%= f.label :defender_king %>
    <%= f.text_field :defender_king %>
  </div>

  <div class="field">
    <%= f.label :attacker_1 %>
    <%= f.text_field :attacker_1 %>
  </div>

  <div class="field">
    <%= f.label :defender_1 %>
    <%= f.text_field :defender_1 %>
  </div>

  <div class="field">
    <%= f.label :battle_outcome %>
    <%= f.text_field :battle_outcome %>
  </div>

  <div class="field">
    <%= f.label :battle_type %>
    <%= f.text_field :battle_type %>
  </div>

  <div class="field">
    <%= f.label :major_deaths %>
    <%= f.number_field :major_deaths %>
  </div>

  <div class="field">
    <%= f.label :major_capture %>
    <%= f.number_field :major_capture %>
  </div>

  <div class="field">
    <%= f.label :attacker_size %>
    <%= f.number_field :attacker_size %>
  </div>

  <div class="field">
    <%= f.label :defender_size %>
    <%= f.number_field :defender_size %>
  </div>

  <div class="field">
    <%= f.label :attacker_commander %>
    <%= f.text_field :attacker_commander %>
  </div>

  <div class="field">
    <%= f.label :defender_commander %>
    <%= f.text_field :defender_commander %>
  </div>

  <div class="field">
    <%= f.label :summer %>
    <%= f.check_box :summer %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :region %>
    <%= f.text_field :region %>
  </div>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/battles/count.html.erb
<div class="container">
	<h1>Total no. of records:<%= @battles_count.count %></h1> 
</div>

app/views/battles/count.json.erb
{
    "No. of Records" : "<%= @battles_count.count %>"
}

app/views/battles/edit.html.erb
<div class="container">
	<h1>Editing Battle</h1>
	<%= render 'form', battle: @battle %>

<%= link_to 'Show', @battle %> |
<%= link_to 'Back', battles_path %>
</div>

app/views/battles/index.html.erb
<%= render 'battles' %>

app/views/battles/new.html.erb
<div class="container">
	<h1>New Battle</h1>

	<%= render 'form', battle: @battle %>

	<%= link_to 'Back', battles_path %>
</div>

app/views/battles/search.html.erb
<div class="">
  <% if @battles.present? %>
    <%= render 'battles' %>
  <% else %>
    <p>There are no battles containing the term(s) <%= params[:search] %>.</p>
  <% end %>
</div>

app/views/battles/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @battle.name %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= @battle.year %>
  </p>

  <p>
    <strong>Battle number:</strong>
    <%= @battle.battle_number %>
  </p>

  <p>
    <strong>Attacker king:</strong>
    <%= @battle.attacker_king %>
  </p>

  <p>
    <strong>Defender king:</strong>
    <%= @battle.defender_king %>
  </p>

  <p>
    <strong>Attacker 1:</strong>
    <%= @battle.attacker_1 %>
  </p>

  <p>
    <strong>Defender 1:</strong>
    <%= @battle.defender_1 %>
  </p>

  <p>
    <strong>Battle outcome:</strong>
    <%= @battle.battle_outcome %>
  </p>

  <p>
    <strong>Battle type:</strong>
    <%= @battle.battle_type %>
  </p>

  <p>
    <strong>Major deaths:</strong>
    <%= @battle.major_deaths %>
  </p>

  <p>
    <strong>Major capture:</strong>
    <%= @battle.major_capture %>
  </p>

  <p>
    <strong>Attacker size:</strong>
    <%= @battle.attacker_size %>
  </p>

  <p>
    <strong>Defender size:</strong>
    <%= @battle.defender_size %>
  </p>

  <p>
    <strong>Attacker commander:</strong>
    <%= @battle.attacker_commander %>
  </p>

  <p>
    <strong>Defender commander:</strong>
    <%= @battle.defender_commander %>
  </p>

  <p>
    <strong>Summer:</strong>
    <%= @battle.summer %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @battle.location %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= @battle.region %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= @battle.note %>
  </p>

  <%= link_to 'Edit', edit_battle_path(@battle) %> |
  <%= link_to 'Back', battles_path %>
</div>

app/views/battles/stats.html.erb
<h2>For stats .json file <%= link_to 'click here', '/stats.json' %></h2>

app/views/battles/stats.json.erb
{  
   "most_active":{  
      "attacker_king":"<%= @most_active_attk[0] %>",
      "defender_king":"<%= @most_active_defk[0] %>",
      "region":"<%= @most_active_region[0] %>",
      "name":"<%= @most_active_name[0] %>"
   },
   
   "battle_type":[<% @battle_type.each do |key, value| %>
                  "<%= key %>",
                    <% end %>],
   "defender_size":{  
      "average":"<%= @sum/@i %>",
      "min":"<%= @min_def_size[1] %>",
      "max":"<%= @max_def_size[0] %>"
   }
}

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <i class="large material-icons prefix" style = "    left: -64px;  bottom: 15px;  font-size: 5rem;    color: #777670;" >search</i>
          <%= form_tag(search_path, :method => :get) do %>
	  		     <%= text_field_tag "search",  params[:search], placeholder: "Search for your favourite Game of Thrones Battles", autocomplete: :off, :class=>"autocomplete z-depth-5", :id => "autocomplete-input" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GotBattles</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'home' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'home' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/battles.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game of Thrones | Battles</title>
    <%= csrf_meta_tags %>

	    <!--   Stylesheets -->
	    <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Roboto:400,400italic,100,100italic,300,300italic,500,500italic,700,700italic,900,900italic', media: 'all'%>
	    <%= stylesheet_link_tag    'http://fonts.googleapis.com/icon?family=Material+Icons'%>
	    <%= stylesheet_link_tag    'materialize.css'%>
	    <%= stylesheet_link_tag    'battles.css' %>


	    <!-- Javascripts -->

	    
	    <%= javascript_include_tag 'https://code.jquery.com/jquery-2.1.1.min.js' %>
	    <%= javascript_include_tag 'materialize.js'%>
	    
	    <%= javascript_include_tag 'battles.js' %>

    </head>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game of Thrones | Battles</title>
    <%= csrf_meta_tags %>

	    <!--   Stylesheets -->
	    <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Roboto:400,400italic,100,100italic,300,300italic,500,500italic,700,700italic,900,900italic', media: 'all'%>
	    <%= stylesheet_link_tag    'http://fonts.googleapis.com/icon?family=Material+Icons'%>
	    <%= stylesheet_link_tag    'materialize.css'%>
	    
	    <%= stylesheet_link_tag    'home.css' %>

	    <!-- Javascripts -->

	    
	    <%= javascript_include_tag 'https://code.jquery.com/jquery-2.1.1.min.js' %>
	    <%= javascript_include_tag 'materialize.js'%>
	    
	    <%= javascript_include_tag 'jquery.soulmate.js' %>
	    <%= javascript_include_tag 'home.js' %>
    </head>
    
  </head>

  <body class = 'body'>
    <%= yield %>
  </body>
</html>